greetings = [
    "Hello World! - K&R original",
    "Hola Mundo! - Spanish",
    "Bonjour le monde! - French",
    "Hallo Welt! - German",
    "Ciao Mondo! - Italian",
    "Olá Mundo! - Portuguese",
    "Hej Verden! - Danish",
    "Witaj świecie! - Polish",
    "Привет, мир! - Russian",
    "こんにちは世界! - Japanese",
    "안녕 세상! - Korean",
    "你好，世界！ - Mandarin Chinese",
    "Sawubona Mhlaba! - Zulu",
    "Howdy, World! - Texan",
    "Yo, World! - AAVE-inspired",
    "Ni hao, World! - Chinatown-style",
    "Aloha Honua! - Hawaiian",
    "Camai, World! - Alaskan (Yup'ik influence)",
    "What’s good, World? - Informal AAVE",
    "Hola, Mundo mío! - Caribbean warmth (Spanish)",
    "Bonjour, cher Monde! - Polite French",
    "Hola Pachamama Mundo! - Andean regions with Quechua influence",
    "Ey, Mundo! - Central American vibe",
    "Totally, World! - Valley talk",
    "Dude, World’s rad today! - Beach talk",
    "Xin chào, World! - Vietnamese-American blend",
    "Annyeong, World! - Korean-American bilingual",
]